bca_web/bca_web/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('main_index.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^members/', include('member_list.urls')),
    url(r'^songs/', include('songs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bca_web/main_index/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'main_index'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	path('accounts/', include('django.contrib.auth.urls')),
	path('signup/', views.signup, name='signup')
]

bca_web/member_list/urls.py
from django.conf.urls import url
from . import views

app_name = 'member_list'
urlpatterns = [
	url(r'^$', views.index, name='member_index')
]

bca_web/songs/urls.py
from django.conf.urls import url
from . import views

app_name = 'songs'
urlpatterns = [
	url(r'^$', views.song_list, name='index'),
	url(r'^new$', views.song_create, name='new'),
	url(r'^edit/(?P<pk>\d+)$', views.song_update, name='edit'),
	url(r'^delete/(?P<pk>\d+)$', views.song_delete, name='delete')
	# url(r'^upload/success/', views.upload_success, name='upload_success'),
	# url(r'^upload', views.upload_song, name='upload')
	
]

bca_web/main_index/models.py
from django.db import models

# Create your models here.

bca_web/member_list/models.py
from django.db import models

# Create your models here.
class Member(models.Model):

	"""
	The core model of a member.
	"""

	member_name = models.CharField(max_length=30)
	graduate_year = models.IntegerField(default=0)
	description_text = models.TextField(max_length=500, default='')

	def __str__(self):
		return 'member_name: ' + self.member_name + ', graduate at: ' + str(self.graduate_year)

bca_web/songs/models.py
from django.db import models
from django.db.models.signals import post_delete

# Create your models here.
class Song(models.Model):

	def __str__(self):
		return self.song_name

	song_name = models.CharField(max_length=30, default='', unique=True)
	song_pdf = models.FileField(upload_to='songs/%Y', default='')

bca_web/main_index/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
	first_name = forms.CharField(max_length=30, required=True, help_text='*')
	last_name = forms.CharField(max_length=30, required=True, help_text='*')
	email= forms.EmailField(max_length=254, help_text='Require a valid email address.')

	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

bca_web/songs/forms.py
from django.forms import ModelForm
from . import models

class SongForm(ModelForm):
	
	class Meta:
		model = models.Song
		fields = ['song_name', 'song_pdf']

bca_web/main_index/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.shortcuts import redirect, render
from . import forms

# Create your views here.
def index(request):
	_context = {}
	return render(request, "main_index/index.html", _context)

def signup(request):
	if request.method == "POST":
		form = forms.SignupForm(request.POST)
		if form.is_valid():
			user = form.save() # Register the user.
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			# user = authenticate(username=username, password=password)
			login(request, user)
			return redirect('main_index:index')
	else:
		form = forms.SignupForm()
	return render(request, "registration/signup.html", { 'form': form })

bca_web/member_list/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import Member

# Create your views here.
def index(request):
	"""
	Note: View only returns a response.
	"""
	_members = Member.objects.order_by('member_name')
	_context = {
		'members': _members
	}
	return render(request, "member_list/index.html", _context)

	

bca_web/songs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib.auth.decorators import login_required
from . import models
from . import forms

# Create your views here.
def song_list(request, template_name='songs/song_list.html'):
	songs = models.Song.objects.all()
	_context = {}
	_context['object_list'] = songs
	return render(request, template_name, _context)

@login_required
def song_create(request, template_name='songs/song_form.html'):
	user = request.user
	if request.method == 'POST':
		# Parse form
		form = forms.SongForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
		return redirect('songs:index')
	else:
		form = forms.SongForm()
	_context = {'form': form}
	return render(request, template_name, _context)

@login_required
def song_update(request, pk, template_name='songs/song_form.html'):
	song = get_object_or_404(models.Song, pk=pk)
	if request.method == 'POST':

		form = forms.SongForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
		return redirect('songs:index')
	else:
		form = forms.SongForm()
	_context = {'form': form}
	return render(request, template_name, _context)

@login_required
def song_delete(request, pk, template_name='songs/song_confirm_delete.html'):
	song = get_object_or_404(models.Song, pk=pk)
	if request.method == 'POST':
		song.delete()
		return redirect('songs:index')
	_context = {'object': song}
	return render(request, template_name, _context)

bca_web/main_index/templates/main_index/index.html
<body>
	<h1> BCA Experimenting Homepage </h1>
	{% if user.is_authenticated %}
		<h2> <a href="{% url 'main_index:logout' %}">LOGOUT</a></h2>
		<h2> <a href="{% url 'member_list:member_index' %}">BCA Member Page </a></h2>
		<h2> <a href="{% url 'songs:index' %}">BCA Song Page</a></h2>
	{% else %}
		<h2> <a href="{% url 'main_index:signup' %}">Sign up</a> or <a href="{% url 'main_index:login' %}">LOGIN</a></h2>
		<h2> <a href="{% url 'member_list:member_index' %}">BCA Member Page </a></h2>
		<h2> <a href="{% url 'songs:index' %}">BCA Song Page</a></h2>
	{% endif %}
</body>

bca_web/member_list/templates/member_list/index.html
<body>
This is bca current members
{% if members %}
	
	{% for m in members %}
	<ul>
		<li> {{ m.member_name }} </li>
		<ul> 
		    <li> Graduation year: {{ m.graduate_year }}</li>
		</ul>
	</ul>
	{% endfor %}
	
{% else %}
	<p> No members are here. </p>
{% endif %}

<a href="{% url 'main_index:index' %}"> Return </a>
</body>

bca_web/songs/templates/songs/song_confirm_delete.html
<form method="post"> {% csrf_token %}
	Are you sure you want to delete "{{ object.song_name }}" ?
	<input type="submit" value="submit" />
</form>
<a href="{% url 'main_index:index' %}">Return</a>

bca_web/songs/templates/songs/song_form.html
<form method="post" enctype="multipart/form-data">{% csrf_token %}
	{{ form.as_p }}
	<br><button type="submit">Upload</button>
</form>
<a href="{% url 'main_index:index' %}">Return</a>

bca_web/songs/templates/songs/song_list.html
{% load static %}
<body>
<h2>This is bca current songs</h2>
<br>

<h3> Admin required: <a href="{% url 'songs:new' %}">**Add Song**</a>
</h3>

{% for s in object_list %}
	<ul>
		<ul> 
		    <li><a href="{{ s.song_pdf.url }}">{{ s.song_name }}<br>
		    <a href="{% url 'songs:edit' s.id %}">  **EDIT**  </a>	||----||
		   	<a href="{% url 'songs:delete' s.id %}">  **DELETE**  </a></li>
		    <li> Other attributes.. (e.g: Author)</li>
		</ul>
	</ul>
{% empty %}
	<p> No songs are here. </p>
{% endfor %}
<a href="{% url 'main_index:index' %}"> Return </a>
</body>